//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement_QuestStuffs
    {
        public int ID { get; set; }
        public byte Enable { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public int CounterTypeID { get; set; }
        public int CounterQuantity { get; set; }
    }
}
