//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement_Data
    {
        public int ID { get; set; }
        public byte ACHIEVEMENT_ENABLE { get; set; }
        public int ACHIEVEMENT_TYPEID { get; set; }
        public string ACHIEVEMENT_NAME { get; set; }
        public int ACHIEVEMENT_QUEST_TYPEID { get; set; }
    }
}
