//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement_QuestItem
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuestTypeID { get; set; }
    }
}
