//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_User_MatchHistory
    {
        public int UID { get; set; }
        public int UID1 { get; set; }
        public int UID2 { get; set; }
        public int UID3 { get; set; }
        public int UID4 { get; set; }
        public int UID5 { get; set; }
    }
}
