//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Server
    {
        public int ServerID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public int MaxUser { get; set; }
        public int UsersOnline { get; set; }
        public int Property { get; set; }
        public long BlockFunc { get; set; }
        public byte ImgNo { get; set; }
        public short ImgEvent { get; set; }
        public byte ServerType { get; set; }
        public bool Active { get; set; }
    }
}
