//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Member
    {
        public int UID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<byte> IDState { get; set; }
        public Nullable<byte> FirstSet { get; set; }
        public Nullable<System.DateTime> LastLogonTime { get; set; }
        public Nullable<byte> Logon { get; set; }
        public string Nickname { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> LogonCount { get; set; }
        public Nullable<byte> Capabilities { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string AuthKey_Login { get; set; }
        public string AuthKey_Game { get; set; }
        public Nullable<int> GUILDINDEX { get; set; }
        public Nullable<int> DailyLoginCount { get; set; }
        public Nullable<byte> Tutorial { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<byte> Event1 { get; set; }
        public Nullable<byte> Event2 { get; set; }
    }
}
