//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Daily_Quest
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public Nullable<int> QuestID1 { get; set; }
        public Nullable<int> QuestID2 { get; set; }
        public Nullable<int> QuestID3 { get; set; }
        public Nullable<System.DateTime> LastAccept { get; set; }
        public Nullable<System.DateTime> LastCancel { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    }
}
