//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Club_Info
    {
        public int ITEM_ID { get; set; }
        public Nullable<short> C0_SLOT { get; set; }
        public Nullable<short> C1_SLOT { get; set; }
        public Nullable<short> C2_SLOT { get; set; }
        public Nullable<short> C3_SLOT { get; set; }
        public Nullable<short> C4_SLOT { get; set; }
        public Nullable<int> CLUB_POINT { get; set; }
        public Nullable<int> CLUB_WORK_COUNT { get; set; }
        public Nullable<int> CLUB_SLOT_CANCEL { get; set; }
        public Nullable<int> CLUB_POINT_TOTAL_LOG { get; set; }
        public Nullable<int> CLUB_UPGRADE_PANG_LOG { get; set; }
    }
}
