//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Caddie
    {
        public int CID { get; set; }
        public int UID { get; set; }
        public int TYPEID { get; set; }
        public int EXP { get; set; }
        public byte cLevel { get; set; }
        public Nullable<int> SKIN_TYPEID { get; set; }
        public Nullable<byte> RentFlag { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> SKIN_END_DATE { get; set; }
        public Nullable<byte> TriggerPay { get; set; }
        public byte VALID { get; set; }
    }
}
