//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Transaction_Log
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string String { get; set; }
        public Nullable<int> ERROR_NUMBER { get; set; }
        public Nullable<int> ERROR_SEVERITY { get; set; }
        public Nullable<int> ERROR_STATE { get; set; }
        public string ERROR_PROCEDURE { get; set; }
        public Nullable<int> ERROR_LINE { get; set; }
        public string ERROR_MESSAGE { get; set; }
    }
}
