//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Locker_Item
    {
        public int INVEN_ID { get; set; }
        public int UID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FROM_ID { get; set; }
        public Nullable<byte> Valid { get; set; }
    }
}
