//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Warehouse
    {
        public int item_id { get; set; }
        public int UID { get; set; }
        public int TYPEID { get; set; }
        public Nullable<short> C0 { get; set; }
        public Nullable<short> C1 { get; set; }
        public Nullable<short> C2 { get; set; }
        public Nullable<short> C3 { get; set; }
        public Nullable<short> C4 { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public byte VALID { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public Nullable<byte> Flag { get; set; }
    }
}
