//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Friend
    {
        public string Owner { get; set; }
        public string Friend { get; set; }
        public byte IsAccept { get; set; }
        public string GroupName { get; set; }
        public byte IsAgree { get; set; }
        public byte IsDeleted { get; set; }
        public string Memo { get; set; }
        public byte IsBlock { get; set; }
    }
}
