//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Exception_Log
    {
        public int ExceptionID { get; set; }
        public Nullable<int> UID { get; set; }
        public string Username { get; set; }
        public string ExceptionMessage { get; set; }
        public string Server { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
