//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Personal
    {
        public int UID { get; set; }
        public Nullable<int> CookieAmt { get; set; }
        public Nullable<int> PangLockerAmt { get; set; }
        public string LockerPwd { get; set; }
    }
}
