//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Mail
    {
        public int Mail_Index { get; set; }
        public int UID { get; set; }
        public string Sender { get; set; }
        public Nullable<int> Sender_UID { get; set; }
        public string Receiver { get; set; }
        public Nullable<int> Receiver_UID { get; set; }
        public string Subject { get; set; }
        public string Msg { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    }
}
