//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Guild_Emblem
    {
        public int EMBLEM_IDX { get; set; }
        public int GUILD_ID { get; set; }
        public string GUILD_MARK_IMG { get; set; }
        public Nullable<byte> GUILD_MARK_ISVALID { get; set; }
    }
}
