//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_User_Message
    {
        public int ID_MSG { get; set; }
        public int UID { get; set; }
        public int UID_FROM { get; set; }
        public byte Valid { get; set; }
        public string Message { get; set; }
        public System.DateTime Reg_Date { get; set; }
    }
}
