//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Guild_Member
    {
        public int GUILD_ID { get; set; }
        public int GUILD_MEMBER_UID { get; set; }
        public Nullable<byte> GUILD_POSITION { get; set; }
        public string GUILD_MESSAGE { get; set; }
        public Nullable<System.DateTime> GUILD_ENTERED_TIME { get; set; }
        public Nullable<byte> GUILD_MEMBER_STATUS { get; set; }
    }
}
