//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Achievement_Quest
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public int Achievement_Index { get; set; }
        public int Achivement_Quest_TypeID { get; set; }
        public int Counter_Index { get; set; }
        public Nullable<System.DateTime> SuccessDate { get; set; }
        public int Count { get; set; }
    }
}
