//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Item_Daily_Log
    {
        public int UID { get; set; }
        public int Counter { get; set; }
        public int Item_TypeID { get; set; }
        public int Item_Quantity { get; set; }
        public int Item_TypeID_Next { get; set; }
        public int Item_Quantity_Next { get; set; }
        public int LoginCount { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
