//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Mail_Item
    {
        public int Mail_Index { get; set; }
        public int TYPEID { get; set; }
        public Nullable<int> SETTYPEID { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<short> DAY { get; set; }
        public string UCC_UNIQUE { get; set; }
        public Nullable<byte> ITEM_GRP { get; set; }
        public Nullable<int> TO_UID { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public Nullable<int> APPLY_ITEM_ID { get; set; }
    }
}
