//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Game_Macro
    {
        public int UID { get; set; }
        public string Macro1 { get; set; }
        public string Macro2 { get; set; }
        public string Macro3 { get; set; }
        public string Macro4 { get; set; }
        public string Macro5 { get; set; }
        public string Macro6 { get; set; }
        public string Macro7 { get; set; }
        public string Macro8 { get; set; }
        public string Macro9 { get; set; }
        public string Macro10 { get; set; }
    }
}
