//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_User_Equip
    {
        public int UID { get; set; }
        public int CADDIE { get; set; }
        public int CHARACTER_ID { get; set; }
        public int CLUB_ID { get; set; }
        public int BALL_ID { get; set; }
        public int ITEM_SLOT_1 { get; set; }
        public int ITEM_SLOT_2 { get; set; }
        public int ITEM_SLOT_3 { get; set; }
        public int ITEM_SLOT_4 { get; set; }
        public int ITEM_SLOT_5 { get; set; }
        public int ITEM_SLOT_6 { get; set; }
        public int ITEM_SLOT_7 { get; set; }
        public int ITEM_SLOT_8 { get; set; }
        public int ITEM_SLOT_9 { get; set; }
        public int ITEM_SLOT_10 { get; set; }
        public int Skin_1 { get; set; }
        public int Skin_2 { get; set; }
        public int Skin_3 { get; set; }
        public int Skin_4 { get; set; }
        public int Skin_5 { get; set; }
        public int Skin_6 { get; set; }
        public int MASCOT_ID { get; set; }
        public int POSTER_1 { get; set; }
        public int POSTER_2 { get; set; }
    }
}
