//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Py_Connector.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ROOM_DATA
    {
        public int IDX { get; set; }
        public int UID { get; set; }
        public int TYPEID { get; set; }
        public Nullable<decimal> POS_X { get; set; }
        public Nullable<decimal> POS_Y { get; set; }
        public Nullable<decimal> POS_Z { get; set; }
        public Nullable<decimal> POS_R { get; set; }
        public Nullable<byte> VALID { get; set; }
        public Nullable<System.DateTime> GETDATE { get; set; }
    }
}
